name: build

on:
  pull_request:
  push:
    branches:
      - master
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
          - macos-latest
        ocaml-compiler:
          - "4.14"
          - "5.2"

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout tree
        uses: actions/checkout@v4

      - name: Set-up OCaml ${{ matrix.ocaml-compiler }}
        uses: kit-ty-kate/setup-ocaml@win52
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          allow-prerelease-opam: true
          dune-cache: true

      - name: Install dependencies on Linux
        if: ${{ runner.os == 'Linux' }}
        run: apt-get install libgmp-dev

      - name: Install deps on macOS
        if: ${{ runner.os == 'macOS' }}
        run: brew install gmp

      - run: ./configure

      - run: opam exec -- make

      - run: opam exec -- make -C tests test

      - run: opam install . --with-test

      - run: git diff --exit-code
